### ISSUE TITLE
net-ldns will not compile on Debian 9 (Stretch

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-ldns#10]
> src/ldns/dane.c:330:14: error: dereferencing pointer to incomplete type
> ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
>    if (vrfy_ctx->error == X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN ||
>                ^~
> Makefile:728: receptet för målet ”src/ldns/dane.o” misslyckades
> 

> # cpan -f -i Net::LDNS
> Loading internal null logger. Install Log::Log4perl for logging messages
> CPAN: Storable loaded ok (v2.56_01)
> Reading '/root/.local/share/.cpan/Metadata'
>    Database was generated on Thu, 18 May 2017 12:53:50 GMT
> Running install for module 'Net::LDNS'
> CPAN: Digest::SHA loaded ok (v5.95_01)
> CPAN: Compress::Zlib loaded ok (v2.069001)
> Checksum for
> /root/.local/share/.cpan/sources/authors/id/C/CD/CDYBED/Net-LDNS-0.75.tar.gz
> ok
> CPAN: File::Temp loaded ok (v0.2304)
> 'YAML' not installed, will not store persistent state
> CPAN: CPAN::Meta::Requirements loaded ok (v2.140)
> CPAN: Parse::CPAN::Meta loaded ok (v1.4417_001)
> CPAN: CPAN::Meta loaded ok (v2.150005)
> CPAN: Module::CoreList loaded ok (v5.20170114_24)
> Configuring C/CD/CDYBED/Net-LDNS-0.75.tar.gz with Makefile.PL
> Writing ppport.h
> ECDSA support detected.
> Your OpenSSL does not seem to support GOST.
> IDNA support detected.
> Checking if your kit is complete...
> Looks good
> Generating a Unix-style Makefile
> Writing Makefile for Net::LDNS
> Writing MYMETA.yml and MYMETA.json
>    CDYBED/Net-LDNS-0.75.tar.gz
>    /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
> Running make for C/CD/CDYBED/Net-LDNS-0.75.tar.gz
> cp lib/Net/LDNS/RR/MX.pm blib/lib/Net/LDNS/RR/MX.pm
> cp lib/Net/LDNS/RR.pm blib/lib/Net/LDNS/RR.pm
> cp lib/Net/LDNS/RR/MF.pm blib/lib/Net/LDNS/RR/MF.pm
> cp lib/Net/LDNS/RR/NSAP.pm blib/lib/Net/LDNS/RR/NSAP.pm
> cp lib/Net/LDNS/RR/NINFO.pm blib/lib/Net/LDNS/RR/NINFO.pm
> cp lib/Net/LDNS/RR/NS.pm blib/lib/Net/LDNS/RR/NS.pm
> cp lib/Net/LDNS/RR/HINFO.pm blib/lib/Net/LDNS/RR/HINFO.pm
> cp lib/Net/LDNS/RR/DNAME.pm blib/lib/Net/LDNS/RR/DNAME.pm
> cp lib/Net/LDNS/Packet.pm blib/lib/Net/LDNS/Packet.pm
> cp lib/Net/LDNS/RR/DLV.pm blib/lib/Net/LDNS/RR/DLV.pm
> cp lib/Net/LDNS/RR/GID.pm blib/lib/Net/LDNS/RR/GID.pm
> cp lib/Net/LDNS/RR/A.pm blib/lib/Net/LDNS/RR/A.pm
> cp lib/Net/LDNS/RR/APL.pm blib/lib/Net/LDNS/RR/APL.pm
> cp lib/Net/LDNS/RR/AAAA.pm blib/lib/Net/LDNS/RR/AAAA.pm
> cp lib/Net/LDNS/RR/L64.pm blib/lib/Net/LDNS/RR/L64.pm
> cp lib/Net/LDNS/RR/MINFO.pm blib/lib/Net/LDNS/RR/MINFO.pm
> cp lib/Net/LDNS/RR/NIMLOC.pm blib/lib/Net/LDNS/RR/NIMLOC.pm
> cp lib/Net/LDNS/RR/NAPTR.pm blib/lib/Net/LDNS/RR/NAPTR.pm
> cp lib/Net/LDNS/RR/MAILA.pm blib/lib/Net/LDNS/RR/MAILA.pm
> cp lib/Net/LDNS/RR/MD.pm blib/lib/Net/LDNS/RR/MD.pm
> cp lib/Net/LDNS/RR/IPSECKEY.pm blib/lib/Net/LDNS/RR/IPSECKEY.pm
> cp lib/Net/LDNS/RR/AFSDB.pm blib/lib/Net/LDNS/RR/AFSDB.pm
> cp lib/Net/LDNS/RR/MG.pm blib/lib/Net/LDNS/RR/MG.pm
> cp lib/Net/LDNS/RR/DHCID.pm blib/lib/Net/LDNS/RR/DHCID.pm
> cp lib/Net/LDNS/RR/HIP.pm blib/lib/Net/LDNS/RR/HIP.pm
> cp lib/Net/LDNS/RR/LOC.pm blib/lib/Net/LDNS/RR/LOC.pm
> cp lib/Net/LDNS/RR/EUI48.pm blib/lib/Net/LDNS/RR/EUI48.pm
> cp lib/Net/LDNS/RR/MR.pm blib/lib/Net/LDNS/RR/MR.pm
> cp lib/Net/LDNS/RR/NID.pm blib/lib/Net/LDNS/RR/NID.pm
> cp lib/Net/LDNS/RR/LP.pm blib/lib/Net/LDNS/RR/LP.pm
> cp lib/Net/LDNS/RR/ATMA.pm blib/lib/Net/LDNS/RR/ATMA.pm
> cp lib/Net/LDNS/RR/CERT.pm blib/lib/Net/LDNS/RR/CERT.pm
> cp lib/Net/LDNS/RR/DNSKEY.pm blib/lib/Net/LDNS/RR/DNSKEY.pm
> cp lib/Net/LDNS/RR/A6.pm blib/lib/Net/LDNS/RR/A6.pm
> cp lib/Net/LDNS.pm blib/lib/Net/LDNS.pm
> cp lib/Net/LDNS/RR/NSEC.pm blib/lib/Net/LDNS/RR/NSEC.pm
> cp lib/Net/LDNS/RR/CDS.pm blib/lib/Net/LDNS/RR/CDS.pm
> cp lib/Net/LDNS/RR/KEY.pm blib/lib/Net/LDNS/RR/KEY.pm
> cp lib/Net/LDNS/RR/EUI64.pm blib/lib/Net/LDNS/RR/EUI64.pm
> cp lib/Net/LDNS/RR/EID.pm blib/lib/Net/LDNS/RR/EID.pm
> cp lib/Net/LDNS/RR/CNAME.pm blib/lib/Net/LDNS/RR/CNAME.pm
> cp lib/Net/LDNS/RR/L32.pm blib/lib/Net/LDNS/RR/L32.pm
> cp lib/Net/LDNS/RR/ISDN.pm blib/lib/Net/LDNS/RR/ISDN.pm
> cp lib/Net/LDNS/RR/CAA.pm blib/lib/Net/LDNS/RR/CAA.pm
> cp lib/Net/LDNS/RR/KX.pm blib/lib/Net/LDNS/RR/KX.pm
> cp lib/Net/LDNS/RR/MAILB.pm blib/lib/Net/LDNS/RR/MAILB.pm
> cp lib/Net/LDNS/RR/MB.pm blib/lib/Net/LDNS/RR/MB.pm
> cp lib/Net/LDNS/RR/GPOS.pm blib/lib/Net/LDNS/RR/GPOS.pm
> cp lib/Net/LDNS/RR/DS.pm blib/lib/Net/LDNS/RR/DS.pm
> cp lib/Net/LDNS/RR/URI.pm blib/lib/Net/LDNS/RR/URI.pm
> cp lib/Net/LDNS/RRList.pm blib/lib/Net/LDNS/RRList.pm
> cp lib/Net/LDNS/RR/TKEY.pm blib/lib/Net/LDNS/RR/TKEY.pm
> cp lib/Net/LDNS/RR/RRSIG.pm blib/lib/Net/LDNS/RR/RRSIG.pm
> cp lib/Net/LDNS/RR/SPF.pm blib/lib/Net/LDNS/RR/SPF.pm
> cp lib/Net/LDNS/RR/UINFO.pm blib/lib/Net/LDNS/RR/UINFO.pm
> cp lib/Net/LDNS/RR/RKEY.pm blib/lib/Net/LDNS/RR/RKEY.pm
> cp lib/Net/LDNS/RR/SRV.pm blib/lib/Net/LDNS/RR/SRV.pm
> cp lib/Net/LDNS/RR/TLSA.pm blib/lib/Net/LDNS/RR/TLSA.pm
> cp lib/Net/LDNS/RR/RP.pm blib/lib/Net/LDNS/RR/RP.pm
> cp lib/Net/LDNS/RR/WKS.pm blib/lib/Net/LDNS/RR/WKS.pm
> cp lib/Net/LDNS/RR/UID.pm blib/lib/Net/LDNS/RR/UID.pm
> cp lib/Net/LDNS/RR/SINK.pm blib/lib/Net/LDNS/RR/SINK.pm
> cp lib/Net/LDNS/RR/SOA.pm blib/lib/Net/LDNS/RR/SOA.pm
> cp lib/Net/LDNS/RR/NSEC3.pm blib/lib/Net/LDNS/RR/NSEC3.pm
> cp lib/Net/LDNS/RR/SIG.pm blib/lib/Net/LDNS/RR/SIG.pm
> cp lib/Net/LDNS/RR/PX.pm blib/lib/Net/LDNS/RR/PX.pm
> cp lib/Net/LDNS/RR/PTR.pm blib/lib/Net/LDNS/RR/PTR.pm
> cp lib/Net/LDNS/RR/NSEC3PARAM.pm blib/lib/Net/LDNS/RR/NSEC3PARAM.pm
> cp lib/Net/LDNS/RR/TXT.pm blib/lib/Net/LDNS/RR/TXT.pm
> cp lib/Net/LDNS/RR/TALINK.pm blib/lib/Net/LDNS/RR/TALINK.pm
> cp lib/Net/LDNS/RR/TYPE.pm blib/lib/Net/LDNS/RR/TYPE.pm
> cp lib/Net/LDNS/RR/TA.pm blib/lib/Net/LDNS/RR/TA.pm
> cp lib/Net/LDNS/RR/RT.pm blib/lib/Net/LDNS/RR/RT.pm
> cp lib/Net/LDNS/RR/NXT.pm blib/lib/Net/LDNS/RR/NXT.pm
> cp lib/Net/LDNS/RR/NULL.pm blib/lib/Net/LDNS/RR/NULL.pm
> cp lib/Net/LDNS/RR/SSHFP.pm blib/lib/Net/LDNS/RR/SSHFP.pm
> cp lib/Net/LDNS/RR/UNSPEC.pm blib/lib/Net/LDNS/RR/UNSPEC.pm
> cp lib/Net/LDNS/RR/X25.pm blib/lib/Net/LDNS/RR/X25.pm
> Running Mkbootstrap for Net::LDNS ()
> chmod 644 "LDNS.bs"
> "/usr/bin/perl" "-Iinc" "/usr/share/perl/5.24/ExtUtils/xsubpp" -typemap
> "/usr/share/perl/5.24/ExtUtils/typemap"  src/LDNS.xs > src/LDNS.xsc &&
> mv src/LDNS.xsc src/LDNS.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/LDNS.o -fPIC
> "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/LDNS.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/assist.o -fPIC
> "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/assist.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/ldns/buffer.o -fPIC
> "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/ldns/buffer.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/ldns/compat/b64_ntop.o
> -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/ldns/compat/b64_ntop.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/ldns/compat/b64_pton.o
> -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/ldns/compat/b64_pton.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/ldns/compat/strlcpy.o
> -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/ldns/compat/strlcpy.c
> x86_64-linux-gnu-gcc -c  "-Iinclude" "-I." "-I." -D_REENTRANT
> -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g  
> -DVERSION=\"0.75\" -DXS_VERSION=\"0.75\" -o src/ldns/dane.o -fPIC
> "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"  -DUSE_PPPORT
> -DWE_CAN_HAZ_IDN src/ldns/dane.c
> src/ldns/dane.c: In function ‘ldns_dane_pkix_get_last_self_signed’:
> src/ldns/dane.c:330:14: error: dereferencing pointer to incomplete type
> ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
>    if (vrfy_ctx->error == X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN ||
>                ^~
> Makefile:728: receptet för målet ”src/ldns/dane.o” misslyckades
> make: *** [src/ldns/dane.o] Fel 1
>    CDYBED/Net-LDNS-0.75.tar.gz
>    make -- NOT OK
>

**Comment by pawal** [comment]
You should perhaps try to upgrade to ldns 1.7.0:
https://git.nlnetlabs.nl/ldns/tree/Changelog?id=release-1.7.0

**Comment by matsduf** [comment]
@pawal, upgrading is probably a good suggestion, but is non-trivial as you know. Zonemaster does not use ldns directly. It is a patched version of it. Do you know if ldns 1.7.0 solves this issue, or is just you guess?

**Comment by pawal** [comment]
I don't find any documentation on the patches of the included ldns in Net::LDNS. But at least one change from Calle is included in the 1.7.0 release. You should probably read through the remaining open issues of ldns to find out if there are more.

There are lots of changes on fixing compiling issues, but also for memory leaks in the newer version. So you should really consider it anyway.

**Comment by pawal** [comment]
https://open.nlnetlabs.nl/pipermail/ldns-users/2016-October/000848.html

**Comment by pawal** [comment]
When will there be a fix available?

**Comment by matsduf** [comment]
This issue will probably be solved by PR #41.

**Comment by matsduf** [comment]
Solved by #41
