### ISSUE TITLE
Make IDN support explicit

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-ldns#24]
Currently the libidn library is auto-detected at compile time and Zonemaster-LDNS adapts accordingly to support IDN or not. If you're not careful it's very easy to end up with a Zonemaster-LDNS without IDN support.

Zonemaster-Backend tests fail if Zonemaster-LDNS lacks IDN support, which prevents installation. The cause of the failure and how to fix it is not at all apparent to the user.

We have no use case for running Zonemaster without IDN support. Compilation of Zonemaster-LDNS should require libidn.

**Comment by mattias-p** [comment]
An alternative solution is to replace the auto-detection with an explicit feature switch that enables IDN support by default.

**Comment by matsduf** [comment]
I support making it explicit with IDN support enabled by default.

**Comment by mattias-p** [comment]
Fixed by #45
