### ISSUE TITLE
Find out the closest possible match between Zonemaster::LDNS C code base and NlnetLabs LDNS C code base

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-ldns#25]
From this point unit tests for Zonemaster::LDNS should be created for every patch and added to Zonemaster::LDNS test list to make sure that in future versions we don't loose the specific use-cases which were the reason for dropping the the use of NLnetLabs LDNS as external library.

**Comment by mattias-p** [comment]
The closest match I've found is zonemaster-ldns abd3e8f4cc42203dfc08a5872be4fa85be3e746b from 2017-12-20 and ldns 726628ba281b6e0cb619e5a9eb303e1ecc9a2011 from 2015-01-26.
As far as I can tell the copied files are identical except for a variable name in b64_pton.c.

**Comment by matsduf** [comment]
@mtoma, is this necessary even if the solution in #40 is accepted?

**Comment by mtoma** [comment]
If we can be sure we are not loosing some patch to LDNS that wouldn't be in the latest LDNS C code it is not necesseary.
Are all the zonemaster engine tests passing using the latest LDSN C files?
When I did the equivalent by replacing all C files from Zonemaster-LDNS by the latest files from Net LDNS they were passing all but one.

**Comment by matsduf** [comment]
@mtoma, yes all tests in LDNS, Engine and CLI passes when using the new LDNS implementation. I have successfully installed the new Zonemaster-LDNS from a distribution package on Ubuntu 16.04, 14.04, CentOS 7 and Debian 7. I have installed LDNS, Engine and CLI.

**Comment by pawal** [comment]
It also works in Debian 8. Haven't tested 9.

**Comment by matsduf** [comment]
@pawal, good to hear. I will test Debian 9 today.

**Comment by matsduf** [comment]
@mtoma, can we close this issue now? I have tested Zonemaster-LDNS from PR #41 on Ubuntu (14.04 and 16.04), CentOS 7 and Debian (7, 8 and 9) with successful results.

**Comment by mtoma** [comment]
Ok, closing the issue. Nice job of integrating the original LDNS!
