### ISSUE TITLE
Unit tests in rr.t fail, make them less picky

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-ldns#26]
Internet has changed again, so two unit tests fail and installation fails. A work-around is to ignore tests depending on Internet:

```
sudo TEST_NO_NETWORK=1 cpan -i Zonemaster::LDNS
```

* For the DNSKEY test, require that at least one key is based on algorithm 8 (and accept other algorithms on other keys).
* For the RRSIG test, expect key tag 59407 for at least one RRSIG, but accept other key tags for other.
* Make "no network" default, and only run the tests that require Internet to be unchanged on demand, i.e. for release tests.

```
t/rr.t ............. 1/?     
    #   Failed test at t/rr.t line 106.
    #          got: '8'
    #     expected: '5'
    
    #   Failed test at t/rr.t line 106.
    #          got: '8'
    #     expected: '5'
    # Looks like you failed 2 tests of 16.

#   Failed test 'DNSKEY'
#   at t/rr.t line 109.
    
    #   Failed test at t/rr.t line 123.
    #          got: '59407'
    #     expected: '59747'
    # Looks like you failed 1 test of 32.

#   Failed test 'RRSIG'
#   at t/rr.t line 128.
# Looks like you failed 2 tests of 15.
t/rr.t ............. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/15 subtests 
```

**Comment by mattias-p** [comment]
Can this be closed?

**Comment by sandoche2k** [comment]
Yes. I tested it.
