### ISSUE TITLE
Missing bits in the installation instructions

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-ldns#34]
Running perl Makefile.PL on a fresh Debian 8 install tells me that there is no Devel::Checklib installed.

**Comment by matsduf** [comment]
Have you tried to install the release on Debian 8? Debian 8 is not supported.

**Comment by pawal** [comment]
I installed the latest from master in Github.

**Comment by matsduf** [comment]
The installation instructions for Zonemaster are based on installation from CPAN. Version 1.0.2 of Zonemaster-LDNS (the latest version at the time of writing) cannot be installed on Debian 8, but if a distribution file is created based on PR #41 (not merged to the develop branch at the time of writing), then that distribution file can be installed by the `cpan` command without the need of `Devel::Checklib`.
