### ISSUE TITLE
Problem building from source on Debian 7

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-ldns#47]
It seems `autoreconf` generates an invalid `configure` on Debian 7. I tried different versions of ldns: the release-1.7.0 tag, current master (470934b7d8cb16e75de4da9fc4da7ab7ddc58cd1) and current develop (853eea97803aad76fc9cec15fbbc9eb1196bbfa3). I get the same behavior on all three.

Here are the ten last lines from the `configure` output:

```
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for doxygen... no
checking for library containing socket... none required
checking for library containing inet_pton... none required
./configure: line 13389: syntax error near unexpected token `newline'
./configure: line 13389: `AX_HAVE_POLL('
```

`configure` scripts generated on Debian 8 can be successfully run on Debian 7.

@sandoche2k Do you think it's important that we either fix this or work around it? Debian 7 is about to reach its end of life.

**Comment by matsduf** [comment]
@sandoche2k, the problem will only be for those that install directly from Git on Debian 7. If you create the dist tar ball on some other machine (e.g. Ubuntu 16.04) then you can install that on Debian 7. That means that if you follow the recommended installation procedure, you will not have any problem.

**Comment by sandoche2k** [comment]
I followed the standard procedure, when i got this issue.

I think we can work around it, since Debian 7 is about to reach its end of
file.

**Comment by sandoche2k** [comment]
Debian 7 will not be supported by Zonemaster as it has reached its End of Life in May 2018.
