### ISSUE TITLE
Allow loading ldns as an ordinary dependency

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-ldns#48]
https://github.com/dotse/zonemaster-engine/issues/26 removed the dependency on ldns. Instead an included version of ldns was statically linked into Zonemaster LDNS (then Net::LDNS). The duplication proved unpopular among packagers. Zonemaster LDNS must be able to properly depend on ldns again. The static linking of a specific version must be available as an option. This options should be enabled by default.

**Comment by mattias-p** [comment]
@sandoche2k @matsduf Can you take a look at this issue description to make sure I don't misrepresent things?

**Comment by matsduf** [comment]
Fine.

**Comment by sandoche2k** [comment]
Ok for me.

**Comment by mattias-p** [comment]
Fixed by #49.
