### ISSUE TITLE
(Zonemaster-Engine) t/dnsset.t fails on some systems

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-ldns#7]
Coming from CPAN testers:

http://analysis.cpantesters.org/reports_by_field?SUBMIT_xxx=Submit&distv=Net-LDNS-0.75&field=conf%3Aosvers&field=meta%3Afrom&field=conf%3Auname&field=fail%3At%2Fdnssec.t

There's no real pattern here. I can just say that on my smoker machines it fails only on a debian/wheezy system with a static IP address. It passes on other machines (various freebsd and debian versions) with a dynamic IP address.

A strace log looks like this --- trying to connecting the given name server fails with timeouts, three times (however, using the "host" programm against the same name server works):

409   21:24:40.770969 socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3 <0.000019>
409   21:24:40.771029 sendto(3, "\324\300\1\0\0\1\0\0\0\0\0\1\3www\3iis\2se\0\0\1\0\1\0\0)\20\0\0\0\200\0\0\0", 39, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("194.146.106.22")}, 16) = 39 <0.000022>
409   21:24:40.771115 select(4, [3], NULL, NULL, {5, 0}) = 0 (Timeout) <5.002892>
409   21:24:45.774080 close(3)          = 0 <0.000022>
409   21:24:45.774148 socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3 <0.000018>
409   21:24:45.774204 sendto(3, "\324\300\1\0\0\1\0\0\0\0\0\1\3www\3iis\2se\0\0\1\0\1\0\0)\20\0\0\0\200\0\0\0", 39, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("194.146.106.22")}, 16) = 39 <0.000025>
409   21:24:45.774291 select(4, [3], NULL, NULL, {5, 0}) = 0 (Timeout) <5.003725>
409   21:24:50.778074 close(3)          = 0 <0.000020>
409   21:24:50.778134 socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 3 <0.000014>
409   21:24:50.778183 sendto(3, "\324\300\1\0\0\1\0\0\0\0\0\1\3www\3iis\2se\0\0\1\0\1\0\0)\20\0\0\0\200\0\0\0", 39, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("194.146.106.22")}, 16) = 39 <0.000027>
409   21:24:50.778265 select(4, [3], NULL, NULL, {5, 0}) = 0 (Timeout) <5.003745>

**Comment by pawal** [comment]
I have a system this fails on now.

```
t/dnssec.t ......... 1/? Could not send or receive, because of network error at t/dnssec.t line 68.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 22.
```

Line 68 in dnssec.t is this:

    my $p1 = $res->query('www.iis.se', 'A');

**Comment by matsduf** [comment]
Seems to be problem with fragmented UDP and not directly ldns related.

**Comment by sandoche2k** [comment]
@mattias-p any update on this issue?

**Comment by matsduf** [comment]
@pawal, have you seen this issue besides from CPAN testing? Have you seen it after creating this issue?

**Comment by pawal** [comment]
It was a long while since I did a fresh install on a system like this.

**Comment by matsduf** [comment]
Thank you, @pawal.

We close this issue now. It will be reopened if we see any issue again.
