### ISSUE TITLE
t/netldns.t fails

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-ldns#9]
The unit test makes assumptions on the DNS data that is no longer true. When running the test:

```
t/netldns.t ........ 1/? 
#   Failed test 'nine authority'
#   at t/netldns.t line 81.
#          got: '10'
#     expected: '9'
# Looks like you failed 1 test of 86.
t/netldns.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/86 subtests 
```

Clean the unit tests from too detailed assumptions.

**Comment by matsduf** [comment]
cpanm -n Net::LDNS

The '-n' flag is allowing it to build by skipping the tests.

**Comment by aabdnn** [comment]
Hi @matsduf. I'm already using '-n' in our build process to skip tests, until this issue is fixed.

**Comment by matsduf** [comment]
@aabdnn, we had another user with the same problem, and I got the work-around from a mail from you. :-)

**Comment by aabdnn** [comment]
This doesn't look like a proper fix. It's just a patch to make this work again for now. If .SE's name servers change, this test will fail again!

**Comment by mattias-p** [comment]
@aabdnn I completely agree with you. This fix is just a stopgap. Properly fixing this is covered by #1.

**Comment by aabdnn** [comment]
Thanks @mattias-p
